// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-H4yjrOgfili4tLNYmUTzq-Jkv4OAm7E',
    appId: '1:1060303999863:web:2b70da663ee577ee450772',
    messagingSenderId: '1060303999863',
    projectId: 'breakup-recovery-2b5zxu',
    authDomain: 'breakup-recovery-2b5zxu.firebaseapp.com',
    storageBucket: 'breakup-recovery-2b5zxu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACAvXueYR2C2cFyYvIUU6IgQUIXqQACoQ',
    appId: '1:1060303999863:android:0ef7fad7c685b5d1450772',
    messagingSenderId: '1060303999863',
    projectId: 'breakup-recovery-2b5zxu',
    storageBucket: 'breakup-recovery-2b5zxu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZqwWikJXWcc4a0Fh8HT_RMGKwsSM2VdU',
    appId: '1:1060303999863:ios:04889bb56a363455450772',
    messagingSenderId: '1060303999863',
    projectId: 'breakup-recovery-2b5zxu',
    storageBucket: 'breakup-recovery-2b5zxu.firebasestorage.app',
    iosBundleId: 'com.breakuprecovery.app',
  );
}
